import "../globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Poppins, Dosis } from "next/font/google";


export const metadata = {
  title: "Boricue",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

const dosis = Dosis({
  weight: ["200", "300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-dosis",
});



export default function RootLayout({ children }) {

  const menu = [
    { name: "Perfil", href: "" },
    { name: "Productos", href: "" },
    { name: "Chat", href: "" },
    { name: "Cerrar sesion", href: "" },
  ]
  return (
    <html lang="es">
      <body
        className={`${dosis.variable} ${poppins.variable} antialiased`}
      >
        <Header menuItems={menu}/>
        <main className="flex flex-col mb-8 w-full items-center ">
          {children}
        </main>
      </body>
    </html>
  );
}
